- name: "Update apt cache"
  become: true
  apt:
    update_cache: yes

- name: "Upgrade apt"
  become: true
  apt:
    upgrade: yes

- name: "Install pm2"
  become: true
  npm:
    name: "pm2"
    global: yes
    production: yes
    state: "present"

- name: "Install other dependency"
  become: true
  apt:
    name: ["tar", "nodejs", "npm"]
    state: "latest"
    update_cache: yes