- name: "Update apt cache"
  become: true
  apt:
    update_cache: yes

- name: "Upgrade apt"
  become: true
  apt:
    upgrade: dist

- name: "Install dependency"
  become: true
  apt:
    name: ["tar", "nodejs", "npm"]
    state: "latest"
    update_cache: yes